doolines:
  development:
    host: http://weixin.doolines.com
    wechat_id: xxxxxxx
    app_id: xxxxxx
    app_secret: xxxxx
    oauth2_redirect_uri: "http://weixin.doolines.com/wechat/users/callback"
    push_url: "http://weixin.doolines.com/wechat/push"
    push_token: xxxxx
  production:
    host: http://weixin.doolines.com

    wechat_id: xxxxxxx
    app_id: xxxxxx
    app_secret: xxxxxxx
